"""empty message

Revision ID: ff8097eeb152
Revises: 
Create Date: 2018-12-15 17:54:43.204877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8097eeb152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contestant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('insta', sa.String(length=256), nullable=False),
    sa.Column('elimated_date', sa.DateTime(), nullable=True),
    sa.Column('is_slops_crew', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower_count_data_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_followers', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('follower_count_data_point')
    op.drop_table('contestant')
    # ### end Alembic commands ###
